FrontMen/resumator

- .eslintrc
- .github/workflows/main.yml
- .prettierrc
- README.md
- package-lock.json
- package.json
- src/App.js
- src/App.test.js
- src/config/theme.js
- src/index.js
- src/serviceWorker.js
- src/setupTests.js
changed base branch to develop instead of master
> Resumator patch 1

- src/components/form/FieldsInput/index.js
- src/pages/PdfCreator.jsx
> feat: split up skills input into fields input

- src/components/form/EducationInput.js
- src/components/form/FieldsInput.js
- src/components/form/MoveControls.js
- src/components/form/index.js
- src/components/form/styledComponents.js
- src/pages/PdfCreator.jsx
> feat: education input

- src/components/form/EducationInput.js
- src/components/form/WorkExperienceInput.js
- src/components/form/index.js
- src/config/theme.js
- src/pages/PdfCreator.jsx
> feat: work experience input

- src/components/FirebaseTest/index.js
It's nice to be able to see the JSON data for development purposes without having to check console sometimes.
> fix: add simple debug data on screen

- package-lock.json
- package.json
- src/components/form/EducationInput.js
- src/components/form/FieldsInput.js
- src/components/form/FormField.js
- src/components/form/MoveControls.js
- src/components/form/WorkExperienceInput.js
- src/components/form/index.js
- src/config/validation.js
- src/pages/PdfCreator.jsx
> feat: form validation config

- src/App.js
- src/components/Debug.jsx
- src/components/ResumeCard.jsx
- src/components/index.js
- src/components/layout/Nav.jsx
- src/components/layout/index.js
- src/config/theme.js
- src/layouts/Login.jsx
- src/layouts/Main.jsx
- src/pages/Overview.jsx
- src/pages/PdfCreator.jsx
- nav and some basic routing
- firestore connection for overview
- submitting now saved mockdata in firestore
- Debug component
> feat: nav, basic routing and firestore connection

- src/components/FormComponents/MoveControls.js
type was missing on middle button ;)
> fix: add type prop to middle swap button

- src/components/CreatorComponents/EducationInput.js
- src/components/CreatorComponents/ExperienceInput.js
- src/components/FormComponents/FieldsInput.js
- src/pages/PdfCreator.jsx
Fixes an issue when removing entries in combination with `useFieldArray`, see: https://github.com/react-hook-form/react-hook-form/issues/1348
> fix: call register method in ref prop

- functions/index.js
Whenever a user logs in for the first time we check if a user already exists (if a resume has already been created for this user by an admin). If so, we merge the user data and assign the correct user data to this person including his resume so he can edit his own resume.
> Added cloudfunction to merge user data

- .github/workflows/main.yml
- src/components/LivePreviewerComponents/LivePreviewerTemplate.jsx
- src/components/LivePreviewerComponents/SideProjectItem.jsx
- src/components/LivePreviewerComponents/SideProjects.jsx
- src/components/PDFBuilderComponents/PDFSideProjects.jsx
- src/pages/Creator/index.jsx
- src/pages/PdfPreviewer/index.jsx
> feat: added open source work and publications

- src/components/LivePreviewerComponents/LivePreviewerTemplate.jsx
- src/components/LivePreviewerComponents/PreviewControls.jsx
added link to download docx file
> added download link

- src/components/LivePreviewerComponents/Experience.jsx
- src/components/LivePreviewerComponents/Skills.jsx
- src/components/LivePreviewerComponents/SkillsSelect.jsx
> [#83] Add skills enhancement

- src/components/LivePreviewerComponents/Education.jsx
- src/components/LivePreviewerComponents/Experience.jsx
- src/components/LivePreviewerComponents/Topsection.jsx
- src/components/constants.js
- This also fixes other places that have the same issue;
- I have changed the import order for the files I've touched to follow the pattern of having from the top having most external modules to bottom having most local modules.
> Missing form values crash #95

- firebase.json
- firebase/indexes.json
- firebase/security.rules
- src/components/layout/Nav.jsx
- src/context/FirebaseContext/index.js
- src/pages/Overview/index.jsx
as a manager I can see and modify all resumes
as a user I can see and modify only my resume
> Manager role 2

- src/components/LivePreviewerComponents/ModalWrapper.jsx
> Cap Modal's width

- server/src/types/index.ts
- src/components/LivePreviewerComponents/LivePreviewerTemplate.jsx
- src/components/LivePreviewerComponents/SideProjects.jsx
- src/config/initialData.js
- src/mock/mock.json
- src/mock/smallmock.json
- src/pages/Creator/index.jsx
- src/pages/PdfPreviewer/index.jsx
- src/utils/useResume.js
This PR also fixes the Edit CV view not having "Side projects" and "Publications" panel if they weren't added during its creation phase.
> Rename "Open source" to "Side projects"

- src/components/LivePreviewerComponents/PreviewControls.jsx
- src/components/layout/Nav.jsx
- src/pages/Overview/index.jsx
I have also refactored some code to improve readability
> UI cleanup

- src/App.js
- src/components/LivePreviewerComponents/PDFPreviewModal.jsx
- src/components/LivePreviewerComponents/PreviewControls.jsx
- src/components/PDFBuilderComponents/PDFHeader.jsx
- src/components/PDFBuilderComponents/ProjectsExperienceCard.jsx
- src/components/PDFDownloadButton/index.jsx
- src/components/PDFTemplate/PDFTemplate.jsx
- src/pages/Overview/index.jsx
- src/pages/PDFDownload/PDFDownload.jsx
- src/pages/PdfPreviewer/index.jsx
- src/utils/getCVFileName.js
- src/utils/getFormattedDate.js
This also fixes the PDF header styling
> Fix PDF download

- functions/local/importDocx.ts
Forgot a key part of the default month setting...
> fix(importDocx): fix default month

- functions/local/importDocx.ts
- functions/package-lock.json
- functions/package.json
The import functionality was broken, revived it but the bug is still there. See story for more details
> chore(import): revive import functionality

- .github/workflows/main.yml
- cached version of npm ci
- removed outdated code
> build: improve CI

- src/components/Form/FormDatePicker.tsx
- src/components/LivePreviewerComponents/EducationItem.tsx
- src/components/PDFBuilderComponents/PDFEducation.jsx
- src/components/PDFBuilderComponents/PDFIntroduction.jsx
- src/components/PDFBuilderComponents/ProjectsExperienceCard.jsx
- src/pages/Overview/AdminView.jsx
- fix education dates in pdf
- add more space between lines in pdf introduction text
- add keyboard support in datepicker
- fix avatar column width in admin view
- add possibility to delete resume from admin view
- remove skills column from admin view
> Various smal fixes

- src/components/LivePreviewerComponents/LivePreviewerTemplate.tsx
- src/components/LivePreviewerComponents/PreviewControls.tsx
- src/components/LivePreviewerComponents/TopSection.tsx
- src/pages/LivePreviewer/index.jsx
> fix: editing resume causing multiple resumes to be added in firestore

- src/context/FirebaseContext/index.js
> feat: switch to saml authentication from intracto

- src/assets/images/avatars/README.md
- src/components/LivePreviewerComponents/TopSection.tsx
> feat: add message add own avatar

- src/components/OverviewDrawer/OverviewSearch.jsx
- src/config/theme.js
Fix material-ui errors in console by using their own suggestions
> chore: fix material-ui errors

- cypress/support/index.d.ts
- src/components/LivePreviewerComponents/LivePreviewerTemplate.tsx
- src/components/LivePreviewerComponents/PreviewControls.tsx
- src/components/LivePreviewerComponents/ResumeModel.ts
- src/components/LivePreviewerComponents/TopSection.tsx
- src/components/OverviewDrawer/OverviewList.tsx
Adds a 'Archive/Unarchive' button on the resume detail page.
Archived resume are displayed at the bottom over de OverviewList
> feat: add functionality to archive/unarchive resume

- package.json
- src/components/Confirmation/Confirmation.tsx
- src/components/__tests__/Confirmation.spec.tsx
Just a start for the code coverage.
We need to pick the rest of the files  one by one to bump our code coverage up to the desired 90%.
> feat(310): add code coverage threshold

- package.json
- yarn.lock
> fix: update vulnerable packages

- src/components/LivePreviewerComponents/SkillChip.tsx
> fix: prevent label from changing size and pushing other labels

- src/components/LivePreviewerComponents/Education.tsx
- src/components/LivePreviewerComponents/Experience.tsx
- src/components/LivePreviewerComponents/LivePreviewerTemplate.tsx
- src/components/LivePreviewerComponents/SectionEditDialog.tsx
- src/components/LivePreviewerComponents/SideProjects.tsx
- src/components/LivePreviewerComponents/SocialLinks.tsx
- src/components/common/Modal.tsx
- src/hooks/useModal.ts
> fix: use close modal anywhere

- src/components/LivePreviewerComponents/SocialLinks.tsx
> fix: fix error while updating social links

- src/components/LivePreviewerComponents/SectionHeader.tsx
- src/components/LivePreviewerComponents/SocialLinks.tsx
> style: fix column width in responsive mode

- src/components/LivePreviewerComponents/Experience.tsx
- src/components/LivePreviewerComponents/ExperienceItem.tsx
- src/components/LivePreviewerComponents/LivePreviewerTemplate.tsx
- src/utils/Skills.ts
- src/utils/index.ts
> feat: add skills by default when new project or experience is added

- package.json
- src/components/Form/FormDatePicker.tsx
- src/components/Form/__snapshots__/FormDatePicker.spec.tsx.snap
- src/components/LivePreviewerComponents/Education.tsx
- src/components/LivePreviewerComponents/Experience.tsx
- src/components/LivePreviewerComponents/PersonaliaDialog.tsx
- src/components/LivePreviewerComponents/SectionEditDialog.tsx
- src/hooks/index.ts
- src/hooks/useStartDate.ts
- src/lib/date.ts
- src/lib/index.ts
> fix: add date validations

- package.json
- src/components/LivePreviewerComponents/Education.spec.tsx
- src/components/LivePreviewerComponents/EducationItem.spec.tsx
- src/components/LivePreviewerComponents/Experience.spec.tsx
- src/components/LivePreviewerComponents/ExperienceItem.spec.tsx
- src/components/LivePreviewerComponents/LivePreviewerTemplate.spec.tsx
- src/components/LivePreviewerComponents/LivePreviewerTemplate.tsx
- src/components/LivePreviewerComponents/Motivation.spec.tsx
- src/components/LivePreviewerComponents/PDFPreviewModal.spec.tsx
- src/components/LivePreviewerComponents/PDFPreviewModal.tsx
- src/components/LivePreviewerComponents/SectionHeader.spec.tsx
- src/components/LivePreviewerComponents/SectionItemHeader.tsx
- src/components/LivePreviewerComponents/TopSection.spec.tsx
- src/mocks/mocks.ts
- Education
- EducationItem
- Experience
- ExperienceItem
- LivePreviewerTemplate
- Motivation
- PDFPreviewModal
> added unit test and mocks for LivePreviewerComponents:
